project_id = "xjpaliwcbwhmzpefigsr"

[functions.send-otp-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false

[functions.send-host-approval-request]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.validate-and-create-booking]
verify_jwt = false

[functions.create-notification]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.admin-bookings]
verify_jwt = false

[functions.admin-venues]
verify_jwt = false

[functions.admin-events]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.send-event-reminder]
verify_jwt = false

[functions.admin-slot-blocks]
verify_jwt = false
