project_id = "xjpaliwcbwhmzpefigsr"

[functions.send-otp-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-booking-reminder]
verify_jwt = false

[functions.send-host-approval-request]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.validate-and-create-booking]
verify_jwt = false